language: python
python:
  - "3.6"

env:
  - DJANGO_VERSION=2.0.5

addons:
  apt_packages:
     - swig
     - libssl-dev
     - libssl0.9.8
     - python-m2crypto
     - libcups2-dev
     - unixodbc-dev
     - python-mysqldb

services:
  - mysql

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

# virtualenv:
#  system_site_packages: true

install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install coveralls
  - pip install pycups
  - pip uninstall -q -r requirements.txt
  - pip install -q -r requirements.txt

before_script:
  #- flake8 edc-pharmacy
  # - mkdir -p crypto_fields/test_keys
    - mysql -e 'create database test_default CHARACTER SET utf8;'
  # - mysql -e 'create database td_lab CHARACTER SET utf8;'

script: 
  - coverage run --source=edc_pharmacy manage.py test

r_github_packages:
  - edc-pharmacy/covr

after_success:
  - coveralls
  - Rscript -e 'covr::coveralls()'
